# ~/.tmuxinator/dockefile.yml

name: dockerfile
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

windows:
  - dockerfile:
      layout: even-vertical
      panes:
        - date
        - date
        - sudo docker help|tail|less
        - sudo docker images |grep -v "<none>"|less
        - sudo docker ps -a|less
  - edit-dockerfile:
      layout: main-vertical
      panes:
        - date
        - date
